### ISSUE TITLE
A little question about "boundary condition"

### ISSUE THREAD

**Issue by henryhudazhi** [Sourangsu/Diffractive-Optics-Code#1]
Excuse me, i don't know the definition of this 'boundary condition'. It also appeared in the article 'Design and analysis of multi-wavelength diffractive optics', 'a unit amplitude boundary condition is assumed'. 
It looks like a kind of limitation of transmission function? 
Could you show me the specific description, please?

**Comment by Sourangsu** [comment]
In simple terms, "boundary condition" refers to the situation of "what happens at the edge of the aperture/object?". 

A more formal and general definition can be found at: https://www.simscale.com/docs/simwiki/numerics-background/what-are-boundary-conditions/

When modeling wave optics (not geometric optics) problems, a full-wave FDTD approach is normally used. From that perspective, a general definition of "boundary conditions" can be found at: Chapter 3 of this book (https://eecs.wsu.edu/~schneidj/ufdtd/)

It looks like a kind of limitation of transmission function?
No, not really. There are various kinds of boundary conditions. It mostly depends on the specific application. For multilevel diffractive optics, I would say that "unit amplitude" makes calculations easy. 

For a pictorial visualization, you look into my OSFDTD codes or some visualizations online to understand: 
https://www.youtube.com/watch?v=XcL9iEK0GDY

Last thing to remember: What I use is scalar diffraction theory (this is a quasi-wave optics approach) compared to full-wave FDTD (which can also be renamed as "vectorial diffraction theory"). But in both cases, the definiton of "boundary condition" remains the same. 

Best of Luck!

**Comment by henryhudazhi** [comment]
Thanks, bro.
Very helpful.
