### ISSUE TITLE
A little confusion about the initial value of DOE

### ISSUE THREAD

**Issue by henryhudazhi** [Sourangsu/Diffractive-Optics-Code#2]
Excuse me,
I read your papers about broadband DOE imaging recently, and i have been confused about the choose of  the initial value of DOE. 
I need much more iterations, and still cannot achieve a good results, is that some tricks to choose the initial value? 
I tried to design a specific wavelength fresnel lens as the initial value (like, 460nm, 550nm, 620nm these three wavelengths, i choose 550nm) in the paper "Chromatic-aberration-corrected diffractive lenses for ultra-broadband focusing". But the result is very poor.
By the way, my initial Figure of Merit is always <0, is that common? 
Thanks.

**Comment by Sourangsu** [comment]
It is a difficult question to answer just like that. I am not aware of any tricks to choose the initial value. But starting with a fresnel phase profile does help (though not always from my own personal experience!). You can take a look at the following papers to see if you find anything useful, I believe they include a discussion on choosing a good initial profile: 
1. https://www.spiedigitallibrary.org/conference-proceedings-of-spie/12072/120720C/Broadband-achromatic-multilevel-diffractive-lens-at-visible-frequency/10.1117/12.2604484.short?SSO=1
2. https://iopscience.iop.org/article/10.1088/1361-6463/abe07d/meta?casa_token=-CXtZuWT2iwAAAAA:Xr_v0OvEl0mvvs4BVvgo0kd7gHmjy9T6vpwZwQ6FGcE-I6DComahXV0sSRyg_ttlvl0z0OhI
 
The initial Figure of Merit is always <0, is that common? Again, it depends on how you set up the optimization. Yes, it is possible if your FoM starts at -100 and goes to 0. But, not the other way around. 

Hope this helps! 

Best,
Sourangsu

**Comment by henryhudazhi** [comment]
Thank you very much again.
